projectile/apidriver/urls.py
# -*- coding: utf-8 -*-

from django.conf.urls import url, patterns


urlpatterns = patterns('c300.adminpanel.views',
    url(r'^$', 'index', name='ap_base'),
    url(r'logout/$', 'ap_logout', name='ap_logout'),

#    url(r'api-street/(?P<type>.*)$', 'street_test', name='street_test'),
    #url(r'testapi/(?P<type>.*)$', 'testapi', name='testapi'),
    url(r'api/street/(?P<type>.*)$', 'street_api', name='street_api'),
    url(r'api/testajax/(?P<url>.*)$', 'test_ajax_to_template',
        name='test_ajax_to_template'),
    url(r'api/kladr/(?P<code>\d+)/(?P<level>[1-5])/$', 'address_list',
        name='kladr_api'),

)

projectile/urls.py
# -*- coding: utf-8 -*-

""" Default urlconf for c300 """
from django.conf import settings
from django.conf.urls.defaults import include, patterns, url
from django.contrib import admin
from django.views.generic.base import TemplateView
admin.autodiscover()

def bad(request):
    """ Simulates a server error """
    1 / 0


from projectile.baseapp.test_api import TestApi
api = TestApi()
from projectile.jproject.api_project import ProjectApi
project_api = ProjectApi()

urlpatterns = patterns('',
    (r'', include('projectile.baseapp.urls', namespace='base')),
    (r'^admin/doc/', include('django.contrib.admindocs.urls')),
    (r'^admin/', include(admin.site.urls)),
    #url(r'^', include('debug_toolbar_user_panel.urls')),
    (r'^bad/$', bad),

    (r'^api-test/', include(api.urls)),
    (r'^api-project/', include(project_api.urls)),
)




## In DEBUG mode, serve media files through Django.
if settings.DEBUG:
    # Remove leading and trailing slashes so the regex matches.
    media_url = settings.MEDIA_URL.lstrip('/').rstrip('/')
    urlpatterns += patterns('',
        (r'^%s/(?P<path>.*)$' % media_url, 'django.views.static.serve',
         {'document_root': settings.MEDIA_ROOT}),
    )

projectile/consumers/forms.py
# -*- coding: utf-8 -*-
from django import forms


class ConsumerLoginForm(forms.Form):
    """
    Форма для входа пользователей
    """
    user_code = forms.CharField(required=True, max_length=50,
                                label=u'Введите имя')
    user_password = forms.CharField(required=True, max_length=15,
                                    widget=forms.PasswordInput(),
                                    label=u'Введите пароль')

projectile/apidriver/templates/adminpanel/ap-auth.html
{% extends "adminpanel/ap-base.html" %}
{% load crispy_forms_tags %}

{% block content %}


<tr class="base">
    <td colspan="2">
        <div id="login" class="" style="width:200px; margin:100px 0 0 35%;">
            {{ message }}
            <form method="post" action="/ap/" class="form-horizontal">
                {% csrf_token %}
                {{ form|crispy }}
                <input type="submit" value="Войти"/>

            </form>
        </div>

    </td>
</tr>

{% endblock %}

projectile/apidriver/templates/adminpanel/ap-base.html
<!doctype html>
<!-- paulirish.com/2008/conditional-stylesheets-vs-css-hacks-answer-neither/ -->
<!--[if lt IE 7]> <html class="no-js lt-ie9 lt-ie8 lt-ie7" lang="en"> <![endif]-->
<!--[if IE 7]>    <html class="no-js lt-ie9 lt-ie8" lang="en"> <![endif]-->
<!--[if IE 8]>    <html class="no-js lt-ie9" lang="en"> <![endif]-->
<!-- Consider adding a manifest.appcache: h5bp.com/d/Offline -->
<!--[if gt IE 8]><!--> <html class="no-js" lang="en"> <!--<![endif]-->
<head>
    <meta charset="utf-8">

    <!-- Use the .htaccess and remove these lines to avoid edge case issues. -->
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">

    <title>Система управления C300</title>
    <meta name="description" content="">

    <!-- Mobile viewport optimized: h5bp.com/viewport -->
    <meta name="viewport" content="width=device-width">

    <link rel="stylesheet" type="text/css" href="{{ STATIC_URL }}css/bootstrap/style.css" />
    <link rel="stylesheet" type="text/css" href="{{ STATIC_URL }}css/ap-boilerplate.css" />
    <link rel="stylesheet" type="text/css" href="{{ STATIC_URL }}jquery-ui/css/redmond/jquery-ui-1.8.22.custom.css" />
    <link rel="stylesheet" type="text/css" href="{{ STATIC_URL }}ap/css/ap-base.css" />

    <!-- All JavaScript at the bottom, except this Modernizr build.  -->
    <script src="{{ STATIC_URL }}js/libs/modernizr-2.5.3.min.js"></script>


</head>

<body>
<!-- Prompt IE 6 users to install Chrome Frame. Remove this if you support IE 6. chromium.org/developers/how-tos/chrome-frame-getting-started -->
<!--[if lt IE 9]><p class=chromeframe>Your browser is <em>ancient!</em> <a href="http://browsehappy.com/">Upgrade to a different browser</a> or <a href="http://www.google.com/chromeframe/?redirect=true">install Google Chrome Frame</a> to experience this site.</p><![endif]-->


<!--<header></header>-->


    <div id="loading-mask" style=""></div>
    <div id="loading">
        <div class="loading-indicator">
            <img src="{{ STATIC_URL }}img/loader.gif" align="absmiddle"/>
        </div>
        <h1>Идёт загрузка</h1>
    </div>


<table id="viewport" style="display:none;">

    <tr class="header"><td colspan="2">
        <div class="navbar navbar-inverse navbar-fixed-top">
            <div class="navbar-inner">
                <div class="header-padding">

                    <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </a>

                    <a class="brand" href="/" style="margin-left:10px;">C300</a>

                    <div class="nav-collapse collapse pull-left">
                        <ul class="nav">
                            <li class=""><a href="/">домой</a></li>
                        </ul>
                    </div>

                    {% if user.is_authenticated %}
                        <form class="ap-loginblock navbar-form pull-right">
                            здравствуйте: <a href="#">{{ user }}</a> |
                            <span><a href="/ap/logout/">выйти</a></span>
                        </form>
                    {% endif %}

                </div>
            </div>
        </div>
    </td></tr>

    {% block content %}
        <tr class="base">
            <td colspan="2">
                something, something, something
            </td>
        </tr>
    {% endblock %}


    <tr class="footer">
        <td colspan="2">
            footer
            <div style="display:none">
                <input id="csrf-token" type="hidden" name="csrfmiddlewaretoken" value="{{ csrf_token }}"/>
            </div>
        </td>
    </tr>

</table>


<div id="alert-container"></div>

<!-- JavaScript at the bottom for fast page loading -->

<!-- Grab Google CDN's jQuery, with a protocol relative URL; fall back to local if offline -->
<!--<script src="//ajax.googleapis.com/ajax/libs/jquery/1.7.1/jquery.min.js"></script>
<script>window.jQuery || document.write('<script src="{{ STATIC_URL }}js/libs/jquery-1.7.1.min.js"><\/script>')</script>-->

<script src="{{ STATIC_URL }}js/libs/jquery-1.8.0.min.js"></script>
<script src="{{ STATIC_URL }}/jquery-ui/js/jquery.ui.core.min.js"></script>
<script src="{{ STATIC_URL }}/jquery-ui/js/jquery.ui.widget.min.js"></script>
<script src="{{ STATIC_URL }}/jquery-ui/js/jquery.ui.accordion.min.js"></script>
<script src="{{ STATIC_URL }}js/libs/jquery.form.js"></script>

<script src="{{ STATIC_URL }}js/libs/bootstrap/alert.js"></script>
<script src="{{ STATIC_URL }}js/libs/bootstrap/modal.js"></script>
<script src="{{ STATIC_URL }}js/libs/bootstrap/tooltip.js"></script>

<!-- scripts concatenated and minified via build script
<script src="{{ STATIC_URL }}js/libs/plugins.js"></script> -->

<script src="{{ STATIC_URL }}ap/js/plugins.js"></script>
<script src="{{ STATIC_URL }}ap/js/script.js"></script>
<script src="{{ STATIC_URL }}ap/js/ap-base.js"></script>
<!-- end scripts -->

</body>
</html>

</body>
</html>

projectile/apidriver/templates/adminpanel/ap-buildings-list.html
<h1>Список домов</h1>
{% for i in grid %}
    <p>{{ i }}</p>
{% endfor %}

projectile/apidriver/templates/adminpanel/ap-default.html
<h1>{{ test }}</h1>

projectile/apidriver/templates/adminpanel/ap-main.html
{% extends "adminpanel/ap-base.html" %}

{% block content %}
<tr class="base">
    <td class="menu">
        <div id="menuList">

            <h3><a href="#">Адреса</a></h3>
            <div class="menu-root open">
                <ul>
                    <li data-tname="aaddress" data-turl="kladr/api/00000000000/1/">Адреса</li>
                    <li data-tname="bbuildings" data-turl="house/api/">Список домов</li>
                    <li data-tname="just_test" data-turl="{% url test_reload_tab %}">test for url api/test</li>
                    <li data-tname="pagination_test" data-turl="{% url table_pagination %}">pagination test</li>
                </ul>
            </div>

            <h3><a href="#">Сотрудники</a></h3>
            <div class="menu-root open">
                <ul>
                    <li data-tname="Классификатор" data-turl="{% url providers:api_common_departments_list %}">Классификатор отделов и должностей</li>
                    <li data-tname="tab6" data-turl="providers_stuff">Справочник отделов и должностей организации</li>
                    <li data-tname="Пользователи" data-turl="{% url consumers:api_consumers_list %}">Список пользователей</li>

                </ul>
            </div>

            <h3><a href="#">Организации</a></h3>
            <div class="menu-root open">
                <ul>
                    <li data-tname="Организации" data-turl="{% url providers:api_provider_list %}">Список организаций</li>
                    <li data-tname="address" data-turl="kladr/api/00000000000/1/">Адреса</li>
                    <li data-tname="tab1" data-turl="dsdsd">Клиентская база"</li>
                </ul>
            </div>

            <h3><a href="#">Журналы</a></h3>
            <div class="menu-root open">
                <ul>
                    <li data-tname="Журнал_заявок" data-turl="{% url logrequest:api_requestlog_list %}">Журнал заявок</li>
                </ul>
            </div>

            <h3><a href="#">Услуги системы</a></h3>
            <div class="menu-root open">
                <ul>
                    <li data-tname="tab1" data-turl="dsdsd">Тарифы и услуги системы</li>
                </ul>
            </div>
            <h3><a href="#">Тарифы</a></h3>
            <div class="menu-root open">
                <ul>
                    <li data-tname="tab1" data-turl="dsdsd">Городские тарифы</li>
                    <li data-tname="tab1" data-turl="dsdsd">Тарифы организации</li>
                </ul>
            </div>


            <h3><a href="#">Обращения клиентов</a></h3>
            <div class="menu-root open">
                <ul>
                    <li data-tname="tab1" data-turl="dsdsd">Техническая поддержка</li>
                    <li data-tname="tab1" data-turl="dsdsd">Бухгалтерия</li>
                    <li data-tname="tab1" data-turl="dsdsd">Юридическая поддержка</li>
                </ul>
            </div>

            <h3><a href="#">Информационный канал</a></h3>
            <div class="menu-root open">
                <ul>
                    <li data-tname="tab1" data-turl="dsdsd">Рассылки по потенциальным клиентам</li>
                    <li data-tname="tab1" data-turl="dsdsd">Информационная рассылка по клиентам</li>
                    <li data-tname="tab1" data-turl="dsdsd">Информационная специализированная рассылка по клиентам</li>
                    <li data-tname="tab1" data-turl="dsdsd">Обращения клиентов</li>
                    <li data-tname="tab1" data-turl="dsdsd">Рассылки клиентов</li>
                    <li data-tname="tab1" data-turl="dsdsd">Обращения жильцов к клиентам</li>
                </ul>
            </div>

            <h3><a href="#">Аналитика и статистика</a></h3>
            <div class="menu-root open">
                <ul>
                    <li data-tname="tab1" data-turl="dsdsd">Потребление энергоресурсов</li>
                    <li data-tname="tab1" data-turl="dsdsd">Статистика заявок</li>
                    <li data-tname="tab1" data-turl="dsdsd">Статистика обращений жильцов</li>
                    <li data-tname="tab1" data-turl="dsdsd">Распределение денежных средств жильцов</li>
                    <li data-tname="tab1" data-turl="dsdsd">Клиентская база</li>
                </ul>
            </div>

            <h3><a href="#">Платежи</a></h3>
            <div class="menu-root open">
                <ul>
                    <li data-tname="tab1" data-turl="dsdsd">Платежи клиентов</li>
                    <li data-tname="tab1" data-turl="dsdsd">Платежи жильцов</li>
                </ul>
            </div>

            <h3><a href="#">Регистрация</a></h3>
            <div class="menu-root open">
                <ul>
                    <li data-tname="Регистрация" data-turl="account/api/check/">Регистрация жильцов/сотрудников</li>
                </ul>
            </div>


        </div>
    </td>
    <td class="center">
        <table id="tabsContainer">
            <tr class="tabslist"><td>

                <ul class="tabListContainer">
                    <!--<li class="closable active" data-tabname="welcome">Информация <i class="icon-remove"></i></li>-->
                </ul>

            </td></tr>
            <tr class="tabBodyTr"><td>

                <div id="tabBody">
                    <ul id="listContetnTabs">
                        <!--<li class="tb-el" id="tabname-welcome">
                            <div class="item">
                                <h3>Приветствуем вас!</h3>

                                <h3>список изменений</h3>
                                <ul>
                                    <li>sdfsd</li>
                                    <li>sdfsd</li>
                                </ul>
                            </div>
                        </li>-->
                    </ul>
                </div>

            </td></tr>
        </table>

    </td>
</tr>
{% endblock %}

projectile/apidriver/templates/adminpanel/ap-prt-table.html
{% for i in list %}

    <tr>
        <td>{{ i.street }}</td>
        <td>{{ i.number }}</td>
    </tr>

{% endfor %}

<tr class="paging-row" data-page="{{ pagination.pag_current }}"><td colspan="1000">
    <div style="float:left;">
        <button class="btn btn-mini" type="button"><i class="icon-step-backward"></i></button>
        <button class="btn-prevpage btn btn-mini" type="button"><i class="icon-arrow-left"></i></button>
        страница <input type="text" value="{{ pagination.pag_current }}"> из {{ pagination.pag_pages }}
        <button class="btn-nextpage btn btn-mini" type="button"><i class="icon-arrow-right"></i></button>
        <button class="btn btn-mini" type="button"><i class="icon-step-forward"></i></button>
    </div>
    <div style="float:right; padding-right:20px;">всего записей: {{ count }}</div>
</td></tr>

projectile/apidriver/templates/adminpanel/ap-test-pagination.html
{{ title }}

<table class="table-pagination table table-condensed table-bordered table-hover" data-turl="{{ test_create_table }}">
    {{ table }}
</table>

projectile/apidriver/templates/adminpanel/ap-test.html
<h1>{{ test }}</h1>

{% for i in grid %}
    id = {{ i.id }} | cache_street {{ i.cache_street }}<br/>
{% endfor %}

<div class="test-alert">loadded alert click</div>
<div class="test-reload">reload this tab with ajax content</div>

projectile/apidriver/templates/adminpanel/ap-test2.html
<h1>{{ test }}</h1>

{% for i in grid %}
    id = {{ i.id }} | cache_street {{ i.cache_street }}<br/>
{% endfor %}

<div class="test-alert">loadded alert click</div>
<div class="test-reload">reload this tab with ajax content</div>

projectile/apidriver/templates/adminpanel/login.html
{% extends "base.html" %}

{% block page_class %}home-page{% endblock %}
{% block content %}

{% if alert %}
<div class="alert fade in alert-success">
    <button class="close" data-dismiss="alert">×</button>
    <span>{{ alert }}</span>
</div>
{% endif %}

{% if user %}
<div id="login" class="span7 offset5">
    <div class="span7"><span>Добро пожаловать, {{user}}</span></div>
    <div class="span2"><a class="btn" href="{% url consumers:logout %}">Выйти</a></div>
    <div class="span2"><a class="btn" href="{% url consumers:reset_password %}">Сбросить пароль</a></div>
</div>
{% else %}
<div id="login" class="span7 offset5">
    <form method="post" action="{% url consumers:login %}">
        {% csrf_token %}
        <div class="span3"><label for="id_user_code">{{form.user_code.label}}</label></div>
        <div class="span3">{{form.user_code}}</div>
        <div class="span3"><label for="id_user_password">{{form.user_password.label}}</label></div>
        <div class="span3">{{form.user_password}}</div>
        <div class="span2 offset2"><input type="submit" value="Войти"/></div>
        <div class="span7"><hr/></div>
        <div class="span2"><a class="btn" href="{% url consumers:registration %}">Регистрация</a></div>
        <div class="span2"><a class="btn" href="{% url consumers:reset_password %}">Сбросить пароль</a></div>
    </form>
</div>

{% endif %}
{% endblock %}

projectile/apidriver/templates/adminpanel/provider-common-departments.html
<h1>{{ title }}</h1>

<div id="departments_container">
    {% if grid %}
    <table class="table">
        <thead>
            <tr>
                <th class="span2" colspan="2">Название</th>
                <th class="span2 offset8"><a href="#"><i class="icon-plus-sign"></i> Добавить отдел</a></th>
            </tr>
        </thead>
        <tbody>
        {% for i in grid %}
            <tr>
                <td class="span2" colspan="2">{{ i.name_full }}</td>
                <td class="span2 offset8"><a href="#"><i class="icon-edit"></i> Редактировать</a><a href="#"><i class="icon-remove"></i> Удалить</a><a href="#"><i class="icon-plus-sign"></i> Добавить должность</a></td>
            </tr>
            {% if i.children %}
                {% for child in i.children %}
            <tr>
                <td class="span1">&nbsp;</td>
                <td class="span2">{{ child.name_full }}</td>
                <td class="span2 offset7"><a href="#"><i class="icon-edit"></i> Редактировать</a><a href="#"><i class="icon-remove"></i> Удалить</a></td>
             </tr>
                {% endfor %}
            {% endif %}
        {% endfor %}
        </tbody>
    </table>
    {% endif %}
</div>

projectile/apidriver/templates/adminpanel/provider-list.html
<div id="providers_container">
    <table class="table">
        <thead>
            <tr>
                <th class="span6">Имя</th>
                <th class="span1">Тип орг-ции</th>
                <th class="span1">Телефон</th>
                <th class="span1">Email</th>
                <th class="span1">Тариф</th>
                <th class="span1"><a href="#"><i class="icon-plus-sign"></i> Добавить организацию</a></th>
            </tr>
        </thead>
        <tbody>
        {% for provider in providers %}
            <tr>
            <td>
                <a href="#">{{ provider.name }}</a></br>
                юр.адрес: {{ provider.address_post }}</br>
                факт.адрес: {{ provider.address_fact }}</br>
            </td>
            <td>{{ provider.organization_type}}</td>
            <td>
                {{ provider.phone }}{% if provider.phone_dop %}</br>{{ provider.phone_dop }}{% endif %}
            </td>
            <td>{{ provider.email }}</td>
            <td>&nbsp;</td>
            <td>
                <span data-turl="providers/api/provider_departments_list/{{provider.id}}" class="clickable"><i class="icon-folder-open"></i>Отделы</span></br>
                <a href="#"><i class="icon-user"></i>Работники</a></br>
                <a href="#"><i class="icon-remove"></i> Удалить</a>
            </td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
</div>